apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test5
  name: test5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test5
    spec:
      containers:
        - image: nginx
          name: test5
          ports:
            - containerPort: 80
          resources: {}
status: {}