apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test3
  name: test3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test3
    spec:
      containers:
        - image: nginx
          name: test3
          ports:
            - containerPort: 80
          resources: {}
status: {}