apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx_add
  name: nginx_add
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx_add
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx_add
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
          resources: {}
status: {}