apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-add3
  name: nginx-add3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-add3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-add3
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
          resources: {}
status: {}